name: "Check caller context"

on:
  workflow_call:

jobs:
  one:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
        include:
          - swift: '5.1.0'
            os: ubuntu-20.04
          - swift: '5.6'
            os: ubuntu-20.04
          - swift: '5.6'
            os: macos-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "MATRIX_CONTEXT"
      - name: Dump user context
        run: |
          echo `id`
          sudo cat /etc/sudoers
      - name: Dump env context
        run: printenv

  two:
    name: Test caller-called context
    uses: ./.github/workflows/called.yml
