name: "Check caller context"

on:
  workflow_call:
    inputs:
      workflow:
        description: Workflow id to check status of
        type: string
        required: false
        default: 'main.yml'

jobs:
  one:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, windows-latest]
        include:
          - swift: '5.1.0'
            os: ubuntu-20.04
          - swift: '5.6'
            os: ubuntu-20.04
          - swift: '5.6'
            os: macos-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "MATRIX_CONTEXT"
      - name: Dump user context
        if: runner.os != 'Windows'
        run: |
          echo `id`
          sudo cat /etc/sudoers
      - name: Dump env context
        if: runner.os != 'Windows'
        run: printenv
      - name: View context attributes
        uses: actions/github-script@v9
        with:
          script: console.log(context)
      - name: Get last run
        uses: actions/github-script@v9
        with:
          result-encoding: json
          script: |
            const { GITHUB_REF_NAME, WORKFLOW } = process.env
            console.log(GITHUB_REF_NAME);
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: WORKFLOW,
              branch: GITHUB_REF_NAME,
              event: context.eventName,
              per_page: 2,
              page: 1
            });
            const success = (runs.data.workflow_runs[0]?.status === 'completed') ||
             (runs.data.workflow_runs[1]?.status === 'completed');
            console.log(runs.data.workflow_runs[0]?.status);
            console.log(runs.data.workflow_runs[1]?.status);
            console.log(success);
        env:
          WORKFLOW: called.yml
