name: CI/CD Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: Create release
        required: false 
        type: boolean
        
defaults:
  run:
    shell: bash

jobs:
  one:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - swift: '5.1.0'
            os: ubuntu-20.04
          - swift: '5.6'
            os: ubuntu-20.04
          - swift: '5.6'
            os: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
      
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
      
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
      
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
      
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
      
    - name: Dump user context
      if: runner.os != 'Windows'
      run: |
        echo `id`
        sudo cat /etc/sudoers
        
    - name: Dump env context
      run: printenv
      
    - name: Get last run
      id: check
      uses: actions/github-script@v6.1.0
      with:
        result-encoding: json
        script: |
          const { GITHUB_REF_NAME, WORKFLOW } = process.env
          console.log(GITHUB_REF_NAME);
          const runs = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: WORKFLOW,
            branch: GITHUB_REF_NAME,
            event: context.eventName,
            per_page: 2,
            page: 1
          });
          const success = (runs.data.workflow_runs[0]?.status === 'completed') ||
            (runs.data.workflow_runs[1]?.status === 'completed');
          console.log(runs.data.workflow_runs[0]?.status);
          console.log(runs.data.workflow_runs[1]?.status);
          return success;
      env:
        WORKFLOW: main.yml
      
    - name: Print cpu cores
      id: os_core
      uses: actions/github-script@v6.1.0
      with:
        result-encoding: json
        script: |
          const { cpus } = require('os');
          console.log(cpus());
        
    - name: View context attributes
      if: steps.check.outputs.result == 'true'
      uses: actions/github-script@v6
      with:
        script: console.log(context)

    - name: Check should proceed running steps
      id: precondition
      uses: ./.github/actions/condition
      with:
        files: |
          lib/**/*
          
    - name: Dump precondition output
      env:
        CONDITION: ${{ steps.precondition.outputs.proceed }}
      run: echo "$CONDITION"
      
    - name: Check script output
      id: script-output
      uses: actions/github-script@v6
      with:
        result-encoding: json
        script: |
          core.setOutput('any_changed', true);
          return { any_changed: true, swift_release: true };
      
    - name: Check script output condition
      if: steps.script-output.outputs.result.any_changed == 'true'
      run: echo hello
      
    - name: Check script output condition
      if: steps.script-output.outputs.any_changed == 'true'
      run: echo hello
      
    - name: Check script output
      id: script-output-str
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          return { any_changed: true, swift_release: true };
      
    - name: Check script output condition
      if: fromJSON(steps.script-output-str.outputs.result).any_changed == 'true'
      run: echo hello

  two:
    uses: ./.github/workflows/called.yml
