name: CI/CD Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: Create release
        required: false 
        type: boolean

jobs:
  one:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
        include:
          - swift: '5.1.0'
            os: ubuntu-20.04
          - swift: '5.6'
            os: ubuntu-20.04
          - swift: '5.6'
            os: macos-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "MATRIX_CONTEXT"
      - name: Dump user context
        run: |
          echo `id`
          sudo cat /etc/sudoers
      - name: Dump env context
        run: printenv
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - name: Get last run
        uses: actions/github-script@v6.1.0
        with:
          result-encoding: json
          script: |
            const { WORKFLOW } = process.env
            console.log(WORKFLOW);
            console.log(context.ref);
            console.log(context.eventName);
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: WORKFLOW,
              event: context.eventName,
              per_page: 1,
              page: 1
            });
            console.log(runs);
        env:
          WORKFLOW: main.yml

  two:
    uses: ./.github/workflows/called.yml
